### ISSUE TITLE
Add C++ code generation GRC support (3.10)

### ISSUE THREAD

**Issue by jwmelto** [CyberRadio/gr-cyberradio#10]
In the GNU Radio Companion (GRC), there is an option to generate code in either Python or C++, but the 3.10 YAML files lack the necessary support.

Specifically, for each block, add 
```yaml
flags: [ python, cpp ]
```

and then (for example)
```yaml
cpp_templates:
  include: ['#include <CyberRadio/vita_udp_rx.h>']
  declarations: 'CyberRadio::vita_udp_rx::sptr ${id};'
  make: 'this->${id} = CyberRadio::vita_udp_rx::make();'
```

I'm still playing but these seem to be the minmal required changes to support C++ code generation. Of course, these portions need to be added for all supported blocks (`vita_udp_rx` was just chosen for illustration).
